### ISSUE TITLE
links not showing as links

### ISSUE THREAD

**Issue by audientmusic** [DanielTamkin/placidity#1]
Hey.  I love your ghost theme.  Two quick issues.  When I'm editing a post, the preview pane shows hyperlinks underlined, but when I publish the post (even though the words are still links), there's no obvious was to tell that the word is a link,  Second, I can't find a way to "sort" posts by tags.  Is that possible?
My blog is stupid....but it's at audientmusic.ghost.io - As an example, here is a post http://audientmusic.ghost.io/2015/08/30/aria-giovanni/
The word "episode" in the second paragraph isn't showing up as a link.
Thanks
Rob

**Comment by DanielTamkin** [comment]
Thanks for the kind words @audientmusic 
I've just [merged a fork](https://github.com/DanielTamkin/placidity/commit/0586258e831ccc5c4a564eb06a0d4a862b58d4d7) that fixes this problem(Thank you @nstapelbroek !)
